import { Lexend } from "next/font/google";
import "./globals.css";
import Header from "@/components/header/Header";
import Footer from "@/components/footer/Footer";
import HotToast from "@/components/hotToast/HotToast";
import { AuthProvider } from "@/context/AuthContext";
const lexend = Lexend({ subsets: ["latin"], weight: ["400", "500", "700"] });

export const metadata = {
  title: "NextJs-TailwindCss-DaisyUi -Laravel-mySql",
  description: "Generated by create Foshati web",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={lexend.className}>
        <AuthProvider>
          <main className="flex flex-col min-h-screen">
            <Header />
            <div className="flex-1 ">
              {children}
              <HotToast />
            </div>
            <Footer />
          </main>
        </AuthProvider>
      </body>
    </html>
  );
}
